name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: npm install
    - name: npm run build
    - name: npm test
    - name: bash <(curl -s https://codecov.io/bash)
